<../../../../../mkconfig

INCLUDES=-I../../../../../module
TARG=\
	ssh-rsa.dis\
	ssh-dsa.dis\

SYSMODULES=\
	factotum.m\
	keyring.m\
	security.m\
	rand.m\
	sys.m\
	draw.m\
	bufio.m\
	string.m\

MODULES=\
        ../../../../../module/authio.m\

DISBIN=$ROOT/dis/auth/proto

<$ROOT/mkfiles/mkdis
